spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/interviewDB
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml